### ISSUE TITLE
I had got error as "redefinition of 'struct i2c_msg'

### ISSUE THREAD

**Issue by osolovyoff** [danjperron/A2D_PIC_RPI#1]
this is i2c-dev error, but how will I fix it?

P.S. redefinition of 'union i2c_smbus_data' too

**Comment by danjperron** [comment]
vbloodv could you be more explicit.  

Where exactly did you have that error.    because of i2c_smbus_data I suppose it is from the Raspberry pi and it's not when you tried to compile the Microchip code.

I need  way more information to figure it out.

Which part you tried to compile?
What  is your compile line ? 
Where the error point to, which file ?

**Comment by osolovyoff** [comment]
@danjperron Thanks you for your answer.

It's problem not are your code. It's bugs into gnublin.h
I commented out #include "linux/i2c.h", because this kernel header of linux and I changed struct i2c_smbus_data...

[link to similar trouble](https://www.raspberrypi.org/forums/viewtopic.php?f=33&t=88029)

P.S. You can remove #include "linux/i2c.h" from your code, but this action to be need  to check
